// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// revert_dist_list_cpp
List revert_dist_list_cpp(int n_t, int n_c, std::vector<int> startn, std::vector<int> endn, std::vector<double> d);
RcppExport SEXP _match2C_revert_dist_list_cpp(SEXP n_tSEXP, SEXP n_cSEXP, SEXP startnSEXP, SEXP endnSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< int >::type n_c(n_cSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type startn(startnSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type endn(endnSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(revert_dist_list_cpp(n_t, n_c, startn, endn, d));
    return rcpp_result_gen;
END_RCPP
}
