# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Revert a treated-to-control distance list.
#'
#' @param n_t Number of treated units
#' @param n_c Number of control units
#' @param startn Vector of starting nodes of edges
#' @param endn Vector of ending nodes of edges
#' @param d Vector of cost associated with edges
#' @export
revert_dist_list_cpp <- function(n_t, n_c, startn, endn, d) {
    .Call(`_match2C_revert_dist_list_cpp`, n_t, n_c, startn, endn, d)
}

